Controllers/ClassController.cs
using System;
using System.Linq;
using DeadNoteNew.Databases;
using DeadNoteNew.Models;
using Microsoft.AspNetCore.Mvc;

namespace DeadNoteNew.Controllers
{
    public class ClassController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ClassController(ApplicationDbContext context)
        {
            _context = context;
        }

        /// <summary>
        /// Get all class which user take part in
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            var uid = Request.Cookies["uid"];

            if (!Utils.CheckGuid(uid)) return Redirect("/Login");

            var guid = Guid.Parse(uid);
            var account = _context.Accounts.Find(guid);

            if (account == null) return Redirect("/Login");

            var accountClasses = _context.Classes.Where(c => c.Accounts.Any(a => a.Id == guid));

            ViewData["account"] = account;

            return View(accountClasses);
        }

        /// <summary>
        /// Delete class with specific id
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public IActionResult Delete(string id)
        {
            if (string.IsNullOrEmpty(id)) return NotFound();

            var guid = Guid.Parse(id);

            var delClass = _context.Classes.Find(guid);
            if (delClass == null) return NotFound();

            var members = _context.Accounts.Where(a => a.Classes.Any(c => c.Id == guid));

            ViewData["delClass"] = delClass;
            ViewData["members"] = members;

            return View();
        }

        /// <summary>
        /// Callback function after user submit delete form, check if user exists and perform delete
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public IActionResult DeleteConfirmed(string id)
        {
            if (string.IsNullOrEmpty(id)) return NotFound();

            var guid = Guid.Parse(id);

            var delClass = _context.Classes.Find(guid);
            if (delClass == null) return NotFound();

            delClass.Status = false;
            _context.Classes.Update(delClass);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        /// <summary>
        /// Get form to create new class, only teacher can create class
        /// </summary>
        /// <returns></returns>
        public IActionResult Create()
        {
            var uid = Request.Cookies["uid"];
            if (!Utils.CheckGuid(uid)) return Redirect("/Login");

            var guid = Guid.Parse(uid);
            var account = _context.Accounts.Find(guid);
            if (account == null) return Redirect("/Register");

            // If user is not teacher redirect to /Class
            if (!account.IsTeacher) return RedirectToAction("Index");
            return View();
        }

        /// <summary>
        /// Callback function for create class, save class to database
        /// </summary>
        /// <param name="subject"></param>
        /// <param name="studentGroup"></param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult Create(string subject, string studentGroup)
        {
            var uid = Request.Cookies["uid"];
            if (!Utils.CheckGuid(uid)) return Redirect("/Login");

            var guid = Guid.Parse(uid);
            var account = _context.Accounts.Find(guid);
            if (account == null) return Redirect("/Login");

            // If user is not teacher redirect to /Class
            if (!account.IsTeacher) return RedirectToAction("Index");

            // Create class name with subject and student group
            if (string.IsNullOrEmpty(subject) || string.IsNullOrEmpty(studentGroup)) return BadRequest();
            var className = $"{subject}_{studentGroup}";

            // Class name exist
            if (_context.Classes.Any(c => c.Name == className))
            {
                ViewData["classNameExist"] = $"{className} already exist.";
                return View("Create");
            }

            var newClass = new Class { Id = Guid.NewGuid(), Name = className, Status = true };
            newClass.Accounts.Add(account);

            _context.Classes.Add(newClass);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        /// <summary>
        /// Leave class, remove the link between student and that class
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public IActionResult Leave(Guid id)
        {
            var uid = Request.Cookies["uid"];

            if (!Utils.CheckGuid(uid)) return Redirect("/Login");

            var guid = Guid.Parse(uid);
            var account = _context.Accounts.Find(guid);
            if (account == null) return Redirect("/Login");

            var leavingClass = _context.Classes.Find(id);
            if (leavingClass == null) return NotFound();

            var members = _context.Accounts.Where(a => a.Classes.Any(c => c.Id == id));

            ViewData["leavingClass"] = leavingClass;
            ViewData["members"] = members;

            return View();
        }
    }
}

Controllers/DeadlineController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using DeadNoteNew.Databases;
using DeadNoteNew.Interfaces;
using DeadNoteNew.Models;
using DeadNoteNew.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MimeKit;

namespace DeadNoteNew.Controllers
{
    public class DeadlineController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ISendMailService _sendMailService;

        /// <summary>
        /// Initialize controller
        /// </summary>
        /// <param name="context"></param>
        /// <param name="sendMailService"></param>
        public DeadlineController(ApplicationDbContext context, ISendMailService sendMailService)
        {
            _context = context;
            _sendMailService = sendMailService;
        }

        public async Task<IActionResult> Index(string sortOrder, string currentFilter, string searchString, int? pageNumber)
        {

            // var uid = Request.Cookies["uid"];

            // if (string.IsNullOrEmpty(uid))
            // {
            //     return Redirect("/Login");
            // }

            // var guid = Guid.Parse(uid);
            // var account = _context.Accounts.Find(guid);

            // if (account == null) return Redirect("/Login");

            // var accountClasses = account.Classes;
            // var result = accountClasses.Select(aClass => aClass.Deadlines).ToList();
            // return View(result);
            ViewData["CurrentSort"] = sortOrder;
            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            IEnumerable<Deadline> DeadlineList = this._context.Deadlines;
            var obj = _context.Deadlines.Where(s => s.Status == true);
            int pageSize = 3;
            return View(await PaginatedList<Deadline>.CreateAsync(obj.AsNoTracking(), pageNumber ?? 1, pageSize));

            // return View(obj);
        }

        /// <summary>
        /// Find all classes base on input id
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public IActionResult Class(string id)
        {
            if (string.IsNullOrEmpty(id)) return NotFound();

            var uid = Request.Cookies["uid"];
            if (!Utils.CheckGuid(uid)) return Redirect("/Login");

            var foundClass = _context.Classes.Find(Guid.Parse(id));
            ViewData["className"] = foundClass.Name;

            var result = _context.Classes.Where(c => c.Id == Guid.Parse(id)).SelectMany(c => c.Deadlines);

            return View(result);
        }

        public IActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// Create new deadline, only teacher can access this function
        /// </summary>
        /// <param name="obj"></param>
        /// <param name="StartTime"></param>
        /// <param name="StartDate"></param>
        /// <param name="EndTime"></param>
        /// <param name="EndDate"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Obsolete]
        public IActionResult Create(Deadline obj, string StartTime, DateTime StartDate, string EndTime, DateTime EndDate)
        {
            if (ModelState.IsValid)
            {
                obj.Status = true;
                DateTime s = StartDate;
                var time = StartTime.Split(":");
                TimeSpan ts = new TimeSpan(int.Parse(time[0]), int.Parse(time[1]), 0);
                s = s.Date + ts;
                obj.StartDate = s;

                DateTime s1 = EndDate;
                var time1 = EndTime.Split(":");
                TimeSpan ts1 = new TimeSpan(int.Parse(time1[0]), int.Parse(time1[1]), 0);
                s1 = s1.Date + ts1;
                obj.EndDate = s1;

                var builder = new BodyBuilder();
                //Giao thuc IO Truyen file
                using (StreamReader SourceReader = System.IO.File.OpenText(@"C:\Users\quocb\RiderProjects\DeadNoteNew\Controllers\Templates\index.html"))
                {
                    builder.HtmlBody = SourceReader.ReadToEnd();
                }
                // replace chữ trong index
                string htmlBody = builder.HtmlBody.Replace("PARTY", obj.Title)
                .Replace("date1", obj.StartDate.ToString())
                .Replace("date2", obj.EndDate.ToString())
                .Replace("Placeholder1", obj.Content)
                .Replace("Placeholder2", "\"Your time is limited, so don’t waste it living someone else’s life\" <br> - <i>Steve Jobs</i>");
                string messagebody = string.Format("{0}", htmlBody);

                //List ra tat ca mail hien co trong table Account
                InternetAddressList list = new InternetAddressList();
                var emailList = this._context.Accounts;
                foreach (var item in emailList)
                {
                    list.Add(new MailboxAddress(item.Email));
                }

                var mailContent = new MailContent();
                // mailContent.To = "LongHBCE150048@fpt.edu.vn";
                mailContent.Subject = "DEADNOTE THÔNG BÁO";
                mailContent.Body = messagebody;
                var rs = _sendMailService.SendMail(mailContent, list);

                TempData["StatusMessage"] = "DeadLine has been added ";
                this._context.Deadlines.Add(obj);
                this._context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        /// <summary>
        /// Get deadline info
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public IActionResult Update(Guid id)
        {
            var obj = this._context.Deadlines.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            ViewData["obj"] = obj;
            return View(obj);
        }

        /// <summary>
        /// Update deadline information
        /// </summary>
        /// <param name="id"></param>
        /// <param name="Title"></param>
        /// <param name="Content"></param>
        /// <param name="StartTime"></param>
        /// <param name="StartDate"></param>
        /// <param name="EndTime"></param>
        /// <param name="EndDate"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(Guid id, string Title, string Content, string StartTime, DateTime StartDate, string EndTime, DateTime EndDate)
        {
            var obj = this._context.Deadlines.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            if (Title == null || Content == null)
            {
                return View(obj);
            }
            obj.Title = Title;
            obj.Content = Content;
            DateTime s = StartDate;
            var time = StartTime.Split(":");
            TimeSpan ts = new TimeSpan(int.Parse(time[0]), int.Parse(time[1]), 0);
            s = s.Date + ts;
            obj.StartDate = s;

            DateTime s1 = EndDate;
            var time1 = EndTime.Split(":");
            TimeSpan ts1 = new TimeSpan(int.Parse(time1[0]), int.Parse(time1[1]), 0);
            s1 = s1.Date + ts1;
            obj.EndDate = s1;
            TempData["StatusMessage"] = "DeadLine has been updated ";
            this._context.Deadlines.Update(obj);
            this._context.SaveChanges();
            return RedirectToAction("Index");
        }


        /// <summary>
        /// Get deadline info
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public IActionResult Delete(Guid id)
        {
            var obj = this._context.Deadlines.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }

        /// <summary>
        /// Delete deadline with specific id, only teacher can access
        /// </summary>
        /// <param name="Id"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(Guid? Id)
        {
            var item = _context.Deadlines.Find(Id);
            // var obj = this._db.Categories.Find(cat_id);
            if (item == null)
            {
                return NotFound();
            }
            item.Status = false;
            IEnumerable<Deadline> deadlines1 = this._context.Deadlines;
            var deadlines = deadlines1.Select(p => p).Where(p => p.Id == Id);
            foreach (var obj in deadlines)
            {
                obj.Status = false;
            }
            TempData["StatusMessage"] = "DeadLine has been delete ";
            this._context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Controllers/JoinController.cs
using System;
using DeadNoteNew.Databases;
using Microsoft.AspNetCore.Mvc;

namespace DeadNoteNew.Controllers
{
    public class JoinController : Controller
    {
        private readonly ApplicationDbContext _context;

        public JoinController(ApplicationDbContext context)
        {
            _context = context;
        }

        /// <summary>
        /// Show form to take user input
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            var uid = Request.Cookies["uid"];
            if (Utils.CheckGuid(uid)) return Redirect("/Login");

            var guid = Guid.Parse(uid);
            var account = _context.Accounts.Find(guid);

            if (account == null) return Redirect("/Register");
            return View();
        }

        /// <summary>
        /// Callback function to join class, if user joined that class, redirect to Class controller,
        ///  else create a link between user and that class
        /// </summary>
        /// <param name="classId"></param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult Index(string classId)
        {
            if (string.IsNullOrEmpty(classId)) return NotFound();

            var parsedId = Guid.Parse(classId);
            var foundClass = _context.Classes.Find(parsedId);

            if (foundClass == null) return NotFound();

            var uid = Request.Cookies["uid"];
            if (string.IsNullOrEmpty(uid))
            {
                return Redirect("/Login");
            }

            var guid = Guid.Parse(uid);
            var account = _context.Accounts.Find(guid);
            if (account == null) return Redirect("/Register");

            // User already in that class
            if (foundClass.Accounts.Contains(account)) return Redirect("/Class");

            foundClass.Accounts.Add(account);
            _context.SaveChanges();
            return Redirect("/Class");
        }
    }
}

Controllers/MemberController.cs
using System;
using System.Linq;
using DeadNoteNew.Databases;
using Microsoft.AspNetCore.Mvc;

namespace DeadNoteNew.Controllers
{
    public class MemberController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MemberController(ApplicationDbContext context)
        {
            _context = context;
        }
        
        public IActionResult Index(Guid id)
        {
            var uid = Request.Cookies["uid"];
            if (!Utils.CheckGuid(uid)) return Redirect("/Login");

            var guid = Guid.Parse(uid);
            var account = _context.Accounts.Find(guid);
            if (account == null) return Redirect("/Login");

            var foundClass = _context.Classes.Find(id);
            if (foundClass == null) return Redirect("/Class");

            var members = _context.Accounts.Where(a => a.Classes.Any(c => c.Id == id));

            ViewData["foundClass"] = foundClass;
            ViewData["members"] = members;
            
            return View();
        }
    }
}

Views/Class/Create.cshtml
@model Class

@{
    ViewData["Title"] = "Create Class";
    var classNameExist = ViewData["classNameExist"];
}

<h1 class="text-center">Create new class</h1>

<form asp-action="Create" method="POST">
    <div class="form-group row align-items-center justify-content-center mt-3">
        <label class="col-sm-2 pt-2" for="subject">Subject: </label>
        <input class="form-control col-sm-4" type="text" id="subject" name="subject" placeholder="Ex: SWP391" required/>
    </div>
    <div class="form-group row align-items-center justify-content-center">
        <label class="col-sm-2 pt-1" for="student-group">Student Group: </label>
        <input class="form-control col-sm-4" type="text" id="student-group" name="studentGroup" placeholder="Ex: SE1504" required/>
    </div>
    
    @if (classNameExist != null)
    {
        <p class="text-center text-danger mt-3">@classNameExist</p>
    }
    
    <div class="row justify-content-center mt-3">
        <input class="btn col-sm-5 btn-primary" type="submit" value="Create">
    </div>
</form>

Views/Class/Delete.cshtml
@{
    ViewData["Title"] = "Delete Class";
    var delClass = ViewData["delClass"] as Class;
    var members = ViewData["members"] as IQueryable<Account>;
}

<h1 class="display-4 text-center">Delete Class: @delClass.Name</h1>

<table class="table table-bordered table-hover table-striped">
    <caption class="text-center">Members in class</caption>
    <thead class="thead-dark">
    <th>ID</th>
    <th>Email</th>
    <th>Full Name</th>
    <th>Gender</th>
    <th>Birthday</th>
    <th>Address</th>
    </thead>

    <tbody>
    @foreach (var member in members)
    {
        <tr>
            <td>@member.Id</td>
            <td>@member.Email</td>
            <td>@member.FullName</td>
            <td>@member.Gender</td>
            <td>@member.Birthday</td>
            <td>@member.Address</td>
        </tr>
    }
    </tbody>
</table>

<h3 class="text-danger text-center">Do you really want to delete this class?</h3>
<h5 class="text-danger text-center">This action cannot be undo!</h5>

<div class="row justify-content-center">
    <a asp-action="DeleteConfirmed" asp-route-id="@delClass.Id" class="btn btn-danger w-25 mt-3 mb-3">Delete</a>
</div>
<div class="row justify-content-center">
    <a href="/Class" class="btn btn-primary w-25">Cancel</a>
</div>

Views/Class/Index.cshtml
@model IQueryable<Class>

@{
    ViewData["Title"] = "Classes";
    var account = ViewData["account"] as Account;
}

@if (account is {IsTeacher: true })
{
    <a class="btn btn-block btn-info mb-3" asp-action="Create">Create Class</a>
}
else
{
    <a class="btn btn-block btn-primary mb-3" asp-controller="Join">Join Class</a>
}

<table class="table table-bordered table-hover table-striped">
    <thead class="thead-dark">
    <th>ID</th>
    <th>Name
    <th class="text-center" colspan="3">Actions</th>
    </thead>

    <tbody>
    @foreach (var item in Model)
    {
        @if (!item.Status) continue;
        <tr>
            <td>@item.Id.ToString().ToUpper()</td>
            <td>@item.Name</td>
            <td class="text-center">
                <a class="btn btn-primary" asp-controller="Deadline" asp-action="Class" asp-route-id="@item.Id">Deadlines</a>
            </td>
            <td class="text-center">
                <a class="btn btn-info" asp-controller="Member" asp-route-id="@item.Id">Members</a>
            </td>
            @if (account is {IsTeacher: true})
            {
                <td class="text-center">
                    <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            }
            else
            {
                <td class="text-center">
                    <a class="btn btn-danger" asp-action="Leave" asp-route-id="@item.Id">Leave</a>
                </td>
            }
        </tr>
    }
    </tbody>
</table>

Views/Class/Leave.cshtml
@{
    ViewData["Title"] = "Leave Class";
    var leavingClass = ViewData["leaveClass"] as Class;
    var members = ViewData["members"] as IQueryable<Account>;
}

<h1 class="text-center display-4">Leave Class: @leavingClass?.Name</h1>

<table class="table table-bordered table-hover table-striped">
    <caption class="text-center">Members in class</caption>
    <thead class="thead-dark">
    <th>ID</th>
    <th>Email</th>
    <th>Full Name</th>
    <th>Gender</th>
    <th>Birthday</th>
    <th>Address</th>
    </thead>

    <tbody>
    @foreach (var member in members)
    {
        <tr>
            <td>@member.Id</td>
            <td>@member.Email</td>
            <td>@member.FullName</td>
            <td>@member.Gender</td>
            <td>@member.Birthday</td>
            <td>@member.Address</td>
        </tr>
    }
    </tbody>
</table>

<h3 class="text-danger text-center">Do you really want to leave this class?</h3>

<a asp-action="DeleteConfirmed" asp-route-id="@if (leavingClass != null) {@leavingClass.Id }" class="btn btn-danger btn-block mt-3 mb-3">Leave</a>
<a href="/Class" class="btn btn-primary btn-block">Cancel</a>